import '../models/trip.dart';

class AzureOpenAIService {
  static Future<String> generateRichIntroduction(TripPlan tripPlan) async {
    // Mock implementation
    return 'Enhanced trip introduction generated by AI';
  }

  static Future<String> generateContent(String prompt) async {
    // Mock implementation for place content generation
    return 'AI-generated content based on the provided prompt: $prompt';
  }
}