class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'Travel Buddy',
      'home': 'Home',
      'explore': 'Explore',
      'trips': 'Trips',
      'community': 'Community',
      'profile': 'Profile',
      'safety_hub': 'Safety Hub',
      'emergency_services': 'Emergency Services',
      'hospitals': 'Hospitals',
      'police_stations': 'Police Stations',
      'safe_places': 'Safe Places',
      'share_location': 'Share My Location',
      'im_safe': "I'm Safe",
      'walk_with_me': 'Walk With Me',
      'crisis_guides': 'Crisis Guides',
      'embassy_help': 'Embassy Help',
      'wallet_stolen': 'Wallet Stolen',
      'phone_lost': 'Phone Lost/Stolen',
      'medical_emergency': 'Medical Emergency',
      'scam_alert': 'Scam Alert',
      'get_directions': 'Get Directions',
      'call': 'Call',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'save': 'Save',
      'edit_profile': 'Edit Profile',
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'nationality': 'Nationality',
      'select_nationality': 'Select Nationality',
      'quick_actions': 'Quick Actions',
      'search': 'Search',
      'nearby_places': 'Nearby Places',
      'favorites': 'Favorites',
      'notifications': 'Notifications',
    },
    'es': {
      'app_name': 'Travel Buddy',
      'home': 'Inicio',
      'explore': 'Explorar',
      'trips': 'Viajes',
      'community': 'Comunidad',
      'profile': 'Perfil',
      'safety_hub': 'Centro de Seguridad',
      'emergency_services': 'Servicios de Emergencia',
      'hospitals': 'Hospitales',
      'police_stations': 'Comisarías',
      'safe_places': 'Lugares Seguros',
      'share_location': 'Compartir Mi Ubicación',
      'im_safe': 'Estoy Seguro',
      'walk_with_me': 'Camina Conmigo',
      'crisis_guides': 'Guías de Crisis',
      'embassy_help': 'Ayuda de Embajada',
      'wallet_stolen': 'Cartera Robada',
      'phone_lost': 'Teléfono Perdido/Robado',
      'medical_emergency': 'Emergencia Médica',
      'scam_alert': 'Alerta de Estafa',
      'get_directions': 'Obtener Direcciones',
      'call': 'Llamar',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'edit_profile': 'Editar Perfil',
      'settings': 'Configuración',
      'language': 'Idioma',
      'select_language': 'Seleccionar Idioma',
      'nationality': 'Nacionalidad',
      'select_nationality': 'Seleccionar Nacionalidad',
      'quick_actions': 'Acciones Rápidas',
      'search': 'Buscar',
      'nearby_places': 'Lugares Cercanos',
      'favorites': 'Favoritos',
      'notifications': 'Notificaciones',
    },
    'fr': {
      'app_name': 'Travel Buddy',
      'home': 'Accueil',
      'explore': 'Explorer',
      'trips': 'Voyages',
      'community': 'Communauté',
      'profile': 'Profil',
      'safety_hub': 'Centre de Sécurité',
      'emergency_services': 'Services d\'Urgence',
      'hospitals': 'Hôpitaux',
      'police_stations': 'Commissariats',
      'safe_places': 'Lieux Sûrs',
      'share_location': 'Partager Ma Position',
      'im_safe': 'Je Suis en Sécurité',
      'walk_with_me': 'Marche Avec Moi',
      'crisis_guides': 'Guides de Crise',
      'embassy_help': 'Aide Ambassade',
      'wallet_stolen': 'Portefeuille Volé',
      'phone_lost': 'Téléphone Perdu/Volé',
      'medical_emergency': 'Urgence Médicale',
      'scam_alert': 'Alerte Arnaque',
      'get_directions': 'Obtenir Directions',
      'call': 'Appeler',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'edit_profile': 'Modifier Profil',
      'settings': 'Paramètres',
      'language': 'Langue',
      'select_language': 'Sélectionner Langue',
      'nationality': 'Nationalité',
      'select_nationality': 'Sélectionner Nationalité',
      'quick_actions': 'Actions Rapides',
      'search': 'Rechercher',
      'nearby_places': 'Lieux à Proximité',
      'favorites': 'Favoris',
      'notifications': 'Notifications',
    },
    'de': {
      'app_name': 'Travel Buddy',
      'home': 'Startseite',
      'explore': 'Erkunden',
      'trips': 'Reisen',
      'community': 'Gemeinschaft',
      'profile': 'Profil',
      'safety_hub': 'Sicherheitszentrum',
      'emergency_services': 'Notdienste',
      'hospitals': 'Krankenhäuser',
      'police_stations': 'Polizeistationen',
      'safe_places': 'Sichere Orte',
      'share_location': 'Standort Teilen',
      'im_safe': 'Ich Bin Sicher',
      'walk_with_me': 'Geh Mit Mir',
      'crisis_guides': 'Krisenführer',
      'embassy_help': 'Botschaftshilfe',
      'wallet_stolen': 'Geldbörse Gestohlen',
      'phone_lost': 'Telefon Verloren/Gestohlen',
      'medical_emergency': 'Medizinischer Notfall',
      'scam_alert': 'Betrugswarnung',
      'get_directions': 'Wegbeschreibung',
      'call': 'Anrufen',
      'loading': 'Laden...',
      'error': 'Fehler',
      'success': 'Erfolg',
      'cancel': 'Abbrechen',
      'save': 'Speichern',
      'edit_profile': 'Profil Bearbeiten',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'select_language': 'Sprache Wählen',
      'nationality': 'Nationalität',
      'select_nationality': 'Nationalität Wählen',
      'quick_actions': 'Schnellaktionen',
      'search': 'Suchen',
      'nearby_places': 'Orte in der Nähe',
      'favorites': 'Favoriten',
      'notifications': 'Benachrichtigungen',
    },
    'zh': {
      'app_name': 'Travel Buddy',
      'home': '首页',
      'explore': '探索',
      'trips': '旅行',
      'community': '社区',
      'profile': '个人资料',
      'safety_hub': '安全中心',
      'emergency_services': '紧急服务',
      'hospitals': '医院',
      'police_stations': '警察局',
      'safe_places': '安全地点',
      'share_location': '分享我的位置',
      'im_safe': '我很安全',
      'walk_with_me': '陪我走',
      'crisis_guides': '危机指南',
      'embassy_help': '大使馆帮助',
      'wallet_stolen': '钱包被盗',
      'phone_lost': '手机丢失/被盗',
      'medical_emergency': '医疗紧急情况',
      'scam_alert': '诈骗警报',
      'get_directions': '获取路线',
      'call': '呼叫',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'cancel': '取消',
      'save': '保存',
      'edit_profile': '编辑个人资料',
      'settings': '设置',
      'language': '语言',
      'select_language': '选择语言',
      'nationality': '国籍',
      'select_nationality': '选择国籍',
      'quick_actions': '快速操作',
      'search': '搜索',
      'nearby_places': '附近地点',
      'favorites': '收藏',
      'notifications': '通知',
    },
    'ja': {
      'app_name': 'Travel Buddy',
      'home': 'ホーム',
      'explore': '探索',
      'trips': '旅行',
      'community': 'コミュニティ',
      'profile': 'プロフィール',
      'safety_hub': '安全センター',
      'emergency_services': '緊急サービス',
      'hospitals': '病院',
      'police_stations': '警察署',
      'safe_places': '安全な場所',
      'share_location': '位置を共有',
      'im_safe': '私は安全です',
      'walk_with_me': '一緒に歩く',
      'crisis_guides': '危機ガイド',
      'embassy_help': '大使館ヘルプ',
      'wallet_stolen': '財布盗難',
      'phone_lost': '電話紛失/盗難',
      'medical_emergency': '医療緊急事態',
      'scam_alert': '詐欺警報',
      'get_directions': '道順を取得',
      'call': '電話',
      'loading': '読み込み中...',
      'error': 'エラー',
      'success': '成功',
      'cancel': 'キャンセル',
      'save': '保存',
      'edit_profile': 'プロフィール編集',
      'settings': '設定',
      'language': '言語',
      'select_language': '言語を選択',
      'nationality': '国籍',
      'select_nationality': '国籍を選択',
      'quick_actions': 'クイックアクション',
      'search': '検索',
      'nearby_places': '近くの場所',
      'favorites': 'お気に入り',
      'notifications': '通知',
    },
  };

  String translate(String key, String languageCode) {
    return _translations[languageCode]?[key] ?? _translations['en']?[key] ?? key;
  }

  String t(String key, String languageCode) => translate(key, languageCode);
}
