import '../models/place.dart';

class MockDealsService {
  static List<Deal> generateMockDeals() {
    return [
      // Stay & Travel Deals
      Deal(
        id: 'deal_hotel_1',
        title: '50% Off Luxury Hotel Stay',
        description: 'Experience luxury at half the price! Premium rooms with city views, complimentary breakfast, and spa access.',
        category: 'hotel',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
        discount: '50% OFF',
        placeName: 'Grand City Hotel',
        originalPrice: 200.0,
        discountedPrice: 100.0,
        currency: 'USD',
        validFrom: DateTime.now(),
        validUntil: DateTime.now().add(const Duration(days: 30)),
        location: 'Downtown',
        details: {'amenities': 'Spa, Pool, Breakfast'},
        terms: ['Valid for new bookings only', 'Subject to availability'],
        providerName: 'Grand City Hotel',
        bookingLink: 'https://booking.com',
        isPremium: true,
      ),
      
      Deal(
        id: 'deal_flight_1',
        title: '30% Off Flight Bookings',
        description: 'Save big on your next adventure! Domestic and international flights with flexible booking options.',
        category: 'flight',
        imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05',
        discount: '30% OFF',
        placeName: 'SkyWings Airlines',
        originalPrice: 500.0,
        discountedPrice: 350.0,
        currency: 'USD',
        validFrom: DateTime.now(),
        validUntil: DateTime.now().add(const Duration(days: 15)),
        location: 'All Destinations',
        details: {'class': 'Economy & Business'},
        terms: ['Minimum 7-day advance booking', 'Excludes holidays'],
        providerName: 'SkyWings Airlines',
        bookingLink: 'https://skywings.com',
      ),

      // Food & Drink Deals
      Deal(
        id: 'deal_restaurant_1',
        title: 'Buy 1 Get 1 Free Dinner',
        description: 'Enjoy our signature dishes with a friend! Valid for all main courses during dinner hours.',
        category: 'restaurant',
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0',
        discount: 'BOGO',
        placeName: 'Bella Vista Restaurant',
        originalPrice: 80.0,
        discountedPrice: 40.0,
        currency: 'USD',
        validFrom: DateTime.now(),
        validUntil: DateTime.now().add(const Duration(days: 7)),
        location: 'Little Italy',
        details: {'cuisine': 'Italian', 'hours': '6PM-10PM'},
        terms: ['Valid Monday-Thursday only', 'Reservation required'],
        providerName: 'Bella Vista Restaurant',
        bookingLink: 'https://bellavista.com',
        isPremium: true,
      ),

      Deal(
        id: 'deal_cafe_1',
        title: '25% Off Coffee & Pastries',
        description: 'Start your day right with freshly brewed coffee and artisan pastries at a great price!',
        category: 'cafe',
        imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb',
        discount: '25% OFF',
        placeName: 'Morning Brew Cafe',
        originalPrice: 15.0,
        discountedPrice: 11.25,
        currency: 'USD',
        validFrom: DateTime.now(),
        validUntil: DateTime.now().add(const Duration(days: 14)),
        location: 'Arts District',
        details: {'specialty': 'Organic Coffee & Fresh Pastries'},
        terms: ['Valid 6AM-11AM only', 'Cannot combine with other offers'],
        providerName: 'Morning Brew Cafe',
        bookingLink: 'https://morningbrew.com',
      ),

      // Shopping Deals
      Deal(
        id: 'deal_shopping_1',
        title: '40% Off Fashion & Accessories',
        description: 'Update your wardrobe with the latest trends! Designer clothes and accessories at unbeatable prices.',
        category: 'fashion',
        imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8',
        discount: '40% OFF',
        placeName: 'Style Central Mall',
        originalPrice: 150.0,
        discountedPrice: 90.0,
        currency: 'USD',
        validFrom: DateTime.now(),
        validUntil: DateTime.now().add(const Duration(days: 21)),
        location: 'Shopping District',
        details: {'brands': 'Premium & Designer Labels'},
        terms: ['Minimum purchase \$50', 'Sale items excluded'],
        providerName: 'Style Central Mall',
        bookingLink: 'https://stylecentral.com',
      ),

      // Experiences Deals
      Deal(
        id: 'deal_tour_1',
        title: 'City Walking Tour - 60% Off',
        description: 'Discover hidden gems and local stories with our expert guides. Small groups, big experiences!',
        category: 'tour',
        imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e',
        discount: '60% OFF',
        placeName: 'Urban Explorer Tours',
        originalPrice: 50.0,
        discountedPrice: 20.0,
        currency: 'USD',
        validFrom: DateTime.now(),
        validUntil: DateTime.now().add(const Duration(days: 10)),
        location: 'Historic Downtown',
        details: {'duration': '3 hours', 'group_size': 'Max 12 people'},
        terms: ['Weather dependent', '24-hour cancellation policy'],
        providerName: 'Urban Explorer Tours',
        bookingLink: 'https://urbanexplorer.com',
        isPremium: true,
      ),

      Deal(
        id: 'deal_museum_1',
        title: 'Museum Entry + Audio Guide',
        description: 'Explore art and history with our comprehensive audio guide. Perfect for culture enthusiasts!',
        category: 'museum',
        imageUrl: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd',
        discount: '35% OFF',
        placeName: 'Metropolitan Art Museum',
        originalPrice: 25.0,
        discountedPrice: 16.25,
        currency: 'USD',
        validFrom: DateTime.now(),
        validUntil: DateTime.now().add(const Duration(days: 60)),
        location: 'Museum Quarter',
        details: {'includes': 'Entry + Audio Guide + Map'},
        terms: ['Valid any day', 'Audio guide in 8 languages'],
        providerName: 'Metropolitan Art Museum',
        bookingLink: 'https://metmuseum.com',
      ),

      // Wellness Deals
      Deal(
        id: 'deal_spa_1',
        title: 'Relaxation Package - 45% Off',
        description: 'Unwind with our signature massage and facial combo. Includes access to sauna and relaxation lounge.',
        category: 'spa',
        imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874',
        discount: '45% OFF',
        placeName: 'Serenity Spa & Wellness',
        originalPrice: 180.0,
        discountedPrice: 99.0,
        currency: 'USD',
        validFrom: DateTime.now(),
        validUntil: DateTime.now().add(const Duration(days: 45)),
        location: 'Wellness District',
        details: {'duration': '2.5 hours', 'includes': 'Massage + Facial + Sauna'},
        terms: ['Advance booking required', 'Valid weekdays only'],
        providerName: 'Serenity Spa & Wellness',
        bookingLink: 'https://serenityspa.com',
        isPremium: true,
      ),

      Deal(
        id: 'deal_gym_1',
        title: 'Monthly Gym Membership',
        description: 'Get fit with unlimited access to our state-of-the-art facility. Includes group classes and personal training session.',
        category: 'gym',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b',
        discount: '50% OFF',
        placeName: 'FitLife Gym & Fitness',
        originalPrice: 80.0,
        discountedPrice: 40.0,
        currency: 'USD',
        validFrom: DateTime.now(),
        validUntil: DateTime.now().add(const Duration(days: 30)),
        location: 'Fitness Center',
        details: {'includes': 'Unlimited access + 1 PT session + Group classes'},
        terms: ['New members only', '3-month minimum commitment'],
        providerName: 'FitLife Gym & Fitness',
        bookingLink: 'https://fitlifegym.com',
      ),
    ];
  }
}