import '../models/place.dart';

class MockDealsService {
  static List<Deal> generateMockDeals() {
    return [
      // Stay & Travel Deals
      Deal(
        id: 'deal_hotel_1',
        title: '50% Off Luxury Hotel Stay',
        description: 'Experience luxury at half the price! Premium rooms with city views, complimentary breakfast, and spa access.',
        discount: '50% OFF',
        placeName: 'Grand City Hotel',
        businessType: 'hotel',
        businessName: 'Grand City Hotel',
        images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945'],
        validUntil: DateTime.now().add(const Duration(days: 30)),
        isActive: true,
        views: 1250,
        claims: 89,
        price: PriceInfo(amount: 100.0, currencyCode: 'USD'),
        isPremium: true,
      ),
      
      Deal(
        id: 'deal_flight_1',
        title: '30% Off Flight Bookings',
        description: 'Save big on your next adventure! Domestic and international flights with flexible booking options.',
        discount: '30% OFF',
        placeName: 'SkyWings Airlines',
        businessType: 'attraction',
        businessName: 'SkyWings Airlines',
        images: ['https://images.unsplash.com/photo-1436491865332-7a61a109cc05'],
        validUntil: DateTime.now().add(const Duration(days: 15)),
        isActive: true,
        views: 2100,
        claims: 156,
        price: PriceInfo(amount: 350.0, currencyCode: 'USD'),
        isPremium: false,
      ),

      // Food & Drink Deals
      Deal(
        id: 'deal_restaurant_1',
        title: 'Buy 1 Get 1 Free Dinner',
        description: 'Enjoy our signature dishes with a friend! Valid for all main courses during dinner hours.',
        discount: 'BOGO',
        placeName: 'Bella Vista Restaurant',
        businessType: 'restaurant',
        businessName: 'Bella Vista Restaurant',
        images: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0'],
        validUntil: DateTime.now().add(const Duration(days: 7)),
        isActive: true,
        views: 890,
        claims: 67,
        price: PriceInfo(amount: 40.0, currencyCode: 'USD'),
        isPremium: true,
      ),

      Deal(
        id: 'deal_cafe_1',
        title: '25% Off Coffee & Pastries',
        description: 'Start your day right with freshly brewed coffee and artisan pastries at a great price!',
        discount: '25% OFF',
        placeName: 'Morning Brew Cafe',
        businessType: 'cafe',
        businessName: 'Morning Brew Cafe',
        images: ['https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb'],
        validUntil: DateTime.now().add(const Duration(days: 14)),
        isActive: true,
        views: 456,
        claims: 23,
        price: PriceInfo(amount: 11.25, currencyCode: 'USD'),
        isPremium: false,
      ),

      // Shopping Deals
      Deal(
        id: 'deal_shopping_1',
        title: '40% Off Fashion & Accessories',
        description: 'Update your wardrobe with the latest trends! Designer clothes and accessories at unbeatable prices.',
        discount: '40% OFF',
        placeName: 'Style Central Mall',
        businessType: 'shop',
        businessName: 'Style Central Mall',
        images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8'],
        validUntil: DateTime.now().add(const Duration(days: 21)),
        isActive: true,
        views: 678,
        claims: 34,
        price: PriceInfo(amount: 90.0, currencyCode: 'USD'),
        isPremium: false,
      ),

      // Experiences Deals
      Deal(
        id: 'deal_tour_1',
        title: 'City Walking Tour - 60% Off',
        description: 'Discover hidden gems and local stories with our expert guides. Small groups, big experiences!',
        discount: '60% OFF',
        placeName: 'Urban Explorer Tours',
        businessType: 'attraction',
        businessName: 'Urban Explorer Tours',
        images: ['https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e'],
        validUntil: DateTime.now().add(const Duration(days: 10)),
        isActive: true,
        views: 1340,
        claims: 78,
        price: PriceInfo(amount: 20.0, currencyCode: 'USD'),
        isPremium: true,
      ),

      Deal(
        id: 'deal_museum_1',
        title: 'Museum Entry + Audio Guide',
        description: 'Explore art and history with our comprehensive audio guide. Perfect for culture enthusiasts!',
        discount: '35% OFF',
        placeName: 'Metropolitan Art Museum',
        businessType: 'attraction',
        businessName: 'Metropolitan Art Museum',
        images: ['https://images.unsplash.com/photo-1554907984-15263bfd63bd'],
        validUntil: DateTime.now().add(const Duration(days: 60)),
        isActive: true,
        views: 567,
        claims: 45,
        price: PriceInfo(amount: 16.25, currencyCode: 'USD'),
        isPremium: false,
      ),

      // Wellness Deals
      Deal(
        id: 'deal_spa_1',
        title: 'Relaxation Package - 45% Off',
        description: 'Unwind with our signature massage and facial combo. Includes access to sauna and relaxation lounge.',
        discount: '45% OFF',
        placeName: 'Serenity Spa & Wellness',
        businessType: 'attraction',
        businessName: 'Serenity Spa & Wellness',
        images: ['https://images.unsplash.com/photo-1544161515-4ab6ce6db874'],
        validUntil: DateTime.now().add(const Duration(days: 45)),
        isActive: true,
        views: 923,
        claims: 56,
        price: PriceInfo(amount: 99.0, currencyCode: 'USD'),
        isPremium: true,
      ),

      Deal(
        id: 'deal_gym_1',
        title: 'Monthly Gym Membership',
        description: 'Get fit with unlimited access to our state-of-the-art facility. Includes group classes and personal training session.',
        discount: '50% OFF',
        placeName: 'FitLife Gym & Fitness',
        businessType: 'attraction',
        businessName: 'FitLife Gym & Fitness',
        images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b'],
        validUntil: DateTime.now().add(const Duration(days: 30)),
        isActive: true,
        views: 445,
        claims: 28,
        price: PriceInfo(amount: 40.0, currencyCode: 'USD'),
        isPremium: false,
      ),
    ];
  }
}