name: Deploy Admin Portal to Azure

on:
  push:
    branches:
      - master
    paths:
      - 'admin/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'admin/package-lock.json'
        
    - name: Install admin dependencies
      run: |
        cd admin
        npm ci
        
    - name: Build admin portal
      run: |
        cd admin
        npm run build
        ls -la dist/
        
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/admin"
        output_location: "dist"