name: Health Check

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check App Health
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://travelbuddy-b2c6hgbbgeh4esdh.eastus2-01.azurewebsites.net)
          if [ $response -eq 200 ]; then
            echo "✅ App is healthy (HTTP $response)"
          else
            echo "❌ App health check failed (HTTP $response)"
            exit 1
          fi

      - name: Check API Endpoints
        run: |
          # Test backend health if available
          backend_response=$(curl -s -o /dev/null -w "%{http_code}" https://travelbuddy-b2c6hgbbgeh4esdh.eastus2-01.azurewebsites.net/api/health || echo "404")
          echo "Backend health: HTTP $backend_response"